### ISSUE TITLE
Continue after losing connection to listener

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/in2out#4]
```
connection closed
Input Connection closed, waiting for new client
terminate called after throwing an instance of 'std::runtime_error'
  what():  Server not configured
```

**Comment by JamesBremner** [comment]
v1.2

**Comment by RmanSC** [comment]
James,
Thanks, works good. Only question:
Why when we disconnect the listener, the app start to search for 127.0.0.1:1379 (even so we put 5000 on input and 5001 on output)?

_no-one is listening
looking for output server 127.0.0.1:1389
connection closed
Input Connection closed, waiting for new client
listening for client on port 5000
No connection could be made because the target machine actively refused it.  Generally, it happens that something is preventing a connection to the port or hostname.  Either there is a firewall blocking the connection  or the process that is hosting the service is not listening on that specific port.
wex::tcp failed connection to server_

**Comment by JamesBremner** [comment]
When you restart the listener, does in2out connect successfully to it on 5001 when new input data arrives?

**Comment by RmanSC** [comment]
Yes, everything's working fine. I'm just wondering, why does 127.0.0.1:1379 show up?

**Comment by JamesBremner** [comment]
Good.  That means that it is just a bug in the instrumentation.  I will open a separate issue.

**Comment by JamesBremner** [comment]
Reported in an email: "When I stop listener it would throw an exception:"

**Comment by RmanSC** [comment]
[21082022 attempt 4.txt](https://github.com/JamesBremner/in2out/files/9388959/21082022.attempt.4.txt)
Please, see attached log file from version 1.2.2. It throw exception after I disconnect the listener app.

**Comment by JamesBremner** [comment]
This is a duplicate of #7
